// === BEGIN AGENT WIRING ===
// Harness: Mastra (TypeScript)
// Generated by skill-forge / agent-forge. Replaces the starter placeholder.
//
// Notes:
// - Mastra ships `mastra dev`, a local playground that hosts this agent in a
//   browser UI for free. For interactive iteration during development, run it
//   from the project root; production web should still use Next.js + AI SDK or
//   Mastra's built-in Hono server. (See profile § "Built-in playground".)
// - The model is passed as an AI SDK provider instance (type-safe). Mastra
//   also accepts a router string like "anthropic/claude-opus-4-7" — see the
//   SKILL comment near `buildModel` for that alternative.
// - Tool registration is an OBJECT (name → tool), not an array. Custom
//   tools and MCP tools are merged with spread.
// === END AGENT WIRING ===

import { Agent } from "@mastra/core/agent";
import { createTool } from "@mastra/core/tools";
// TODO: verify — `createTool` is the documented server-side helper from
// `@mastra/core/tools`. A second `createTool` exists in `@mastra/client-js`
// for browser/client tools — do NOT import that one here.
import { MCPClient } from "@mastra/mcp";
import { anthropic } from "@ai-sdk/anthropic";
// SKILL: swap the provider import if state.harness.modelId targets a non-Anthropic
// model — e.g. `import { openai } from "@ai-sdk/openai"` and use openai("gpt-5.4").
import { z } from "zod";

// SKILL: persistence — if state.ux.persistence is set, wire memory like so:
//   import { Memory } from "@mastra/memory";
//   import { LibSQLStore } from "@mastra/libsql";
//   const memory = new Memory({
//     storage: new LibSQLStore({ url: "file:./memory.db" }),
//     options: { lastMessages: 20 },
//   });
//   ...then pass `memory` to `new Agent({ ..., memory })` below, and thread
//   `{ memory: { thread, resource } }` into `agent.stream(input, opts)`.

// ---------------------------------------------------------------------------
// AgentEvent — re-exported so callers (cli/web/electron starters) can import
// from this module and stay decoupled from the harness internals.
// ---------------------------------------------------------------------------
export type AgentEvent =
  | { type: "text"; delta: string }
  | { type: "tool_use"; id: string; name: string; input: any }
  | { type: "tool_result"; id: string; result: any; isError?: boolean }
  | { type: "error"; error: string };

// ---------------------------------------------------------------------------
// Prompt + config
// ---------------------------------------------------------------------------
const SYSTEM_PROMPT = `You are a helpful assistant.
// SKILL: replace this entire string from state.agent.systemPrompt.`;

// SKILL: append MCP server entries from state.tools.mcpServers. Each value is
// either { command, args, env? } for stdio or { url } for HTTP/SSE. Leave the
// object empty to skip MCP entirely.
const MCP_SERVERS: Record<string, any> = {
  // wikipedia: { command: "npx", args: ["-y", "wikipedia-mcp"] },
  // weather: { url: new URL("https://server.smithery.ai/.../mcp?api_key=...") },
};

// SKILL: add custom tools here. Each is built with `createTool` from
// `@mastra/core/tools` and keyed by id. They merge with MCP tools at agent
// construction time. The placeholder `_echo` is illustrative — remove it once
// real tools land. Mastra requires the tools field to be a plain object.
const TOOLS: Record<string, ReturnType<typeof createTool>> = {
  // _echo: createTool({
  //   id: "echo",
  //   description: "Echo the input text",
  //   inputSchema: z.object({ text: z.string() }),
  //   outputSchema: z.object({ echoed: z.string() }),
  //   execute: async ({ context }) => ({ echoed: context.text }),
  // }),
};

// Touch `z` so unused-import lints stay quiet until real tools land.
void z;

// SKILL: model selection — docs-default per profile. state.harness.modelId can
// override. Alternative call form (no provider import needed):
//   model: "anthropic/claude-opus-4-7"   // router string, resolves at runtime
// We use the provider-instance form for stronger types and a fixed dependency.
const MODEL_ID = process.env.AGENT_MODEL_ID ?? "claude-opus-4-7";

function buildModel() {
  return anthropic(MODEL_ID);
}

// ---------------------------------------------------------------------------
// Retry helper — SKILL: configure maxAttempts / baseDelayMs from state.ux.retry.
// ---------------------------------------------------------------------------
async function withRetry<T>(
  factory: () => Promise<T>,
  opts: { maxAttempts?: number; baseDelayMs?: number } = {},
): Promise<T> {
  const maxAttempts = opts.maxAttempts ?? 3;
  const baseDelayMs = opts.baseDelayMs ?? 500;
  let lastErr: unknown;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      return await factory();
    } catch (err) {
      lastErr = err;
      if (attempt === maxAttempts - 1) throw err;
      await new Promise((r) => setTimeout(r, baseDelayMs * 2 ** attempt));
    }
  }
  throw lastErr;
}

// ---------------------------------------------------------------------------
// streamAgent — the public contract.
// ---------------------------------------------------------------------------
export async function* streamAgent(
  prompt: string,
  history?: any[],
): AsyncGenerator<AgentEvent> {
  let mcpClient: MCPClient | null = null;
  try {
    // ---- MCP tools: instantiate the client only if servers are configured ----
    let mcpTools: Record<string, any> = {};
    if (Object.keys(MCP_SERVERS).length > 0) {
      mcpClient = new MCPClient({ id: "agent-mcp", servers: MCP_SERVERS });
      // `listTools()` returns an object keyed by tool name, already in the
      // shape Mastra's `tools` field expects (verified in harness profile).
      mcpTools = await mcpClient.listTools();
    }

    // ---- Build the agent ----
    const agent = new Agent({
      id: "agent",
      name: "Agent",
      instructions: SYSTEM_PROMPT,
      model: buildModel(),
      tools: { ...TOOLS, ...mcpTools },
      // SKILL: if state.ux.persistence is set, add `memory: <Memory instance>`
      // here (see the persistence SKILL comment near the imports).
    });

    // ---- Compose input: thread prior history if the caller supplied it ----
    const input: any =
      history && history.length > 0
        ? [...history, { role: "user", content: prompt }]
        : prompt;

    // ---- Stream ----
    // `agent.stream` returns a Mastra MastraModelOutput. Iterate `.fullStream`
    // to receive typed chunks for text deltas, tool calls, tool results,
    // errors, and the terminal `finish` chunk.
    const stream = await withRetry(() => agent.stream(input));

    for await (const chunk of stream.fullStream) {
      switch (chunk.type) {
        case "text-delta": {
          const text = chunk.payload?.text ?? "";
          if (text) yield { type: "text", delta: text };
          break;
        }
        case "tool-call": {
          yield {
            type: "tool_use",
            id: chunk.payload?.toolCallId ?? "",
            name: chunk.payload?.toolName ?? "",
            input: chunk.payload?.args ?? {},
          };
          break;
        }
        case "tool-result": {
          const ev: AgentEvent = {
            type: "tool_result",
            id: chunk.payload?.toolCallId ?? "",
            result: chunk.payload?.result,
          };
          if (chunk.payload?.isError) ev.isError = true;
          yield ev;
          break;
        }
        case "error": {
          // SKILL: route through state.ux.errorPolicy (classify / redact) here.
          const err = chunk.payload?.error;
          const msg = err instanceof Error ? err.message : String(err);
          yield { type: "error", error: msg };
          break;
        }
        // 'finish', 'reasoning-delta', 'tool-call-delta', 'step-start',
        // 'tool-call-approval', 'tripwire', etc. are intentionally ignored —
        // they are not part of the AgentEvent contract. SKILL: add cases here
        // if the produced agent needs reasoning streams, approval gates, or
        // guardrail tripwires.
        default:
          break;
      }
    }
  } catch (err) {
    // SKILL: route through state.ux.errorPolicy here too — this catches
    // failures that occur outside the stream (agent construction, MCP startup,
    // retry exhaustion) rather than inside Mastra's error chunk.
    const msg = err instanceof Error ? `${err.name}: ${err.message}` : String(err);
    yield { type: "error", error: msg };
  } finally {
    // Best-effort MCP client cleanup. TODO: verify exact teardown method
    // against installed `@mastra/mcp` version (`disconnect()` per docs).
    if (mcpClient) {
      try {
        await mcpClient.disconnect();
      } catch {
        // swallow — teardown errors shouldn't mask a useful upstream error
      }
    }
  }
}
